# Volume indicators
## Ease of Movement indicators

In [2]:
# EASE OF MOVEMENT INDICATOR for Tesla

import yfinance as yf
import pandas as pd
import numpy as np

Tickers=["tsla"] 

df=yf.download(Tickers, start="2021-05-23",end="2023-05-23")  # time period to be observed

high,low,volume,close=df["High"],df["Low"],df["Volume"],df["Close"]

scale=100000000  #selected according to the volumes

list_emvs=["NaN"]    #list that contains all emvs and it will be calculated from day 2 so 1st day NaN

def dist_moved(high,low,PH,PL):   #PH-prior high, PL-prior low
    dist_moved=((high+low)/2)-((PH+PL)/2)    #function clculating distance moved
    return dist_moved

def box_ratio(high,low,volume):
    box_ratio=(volume/scale)/(high-low)   #function calculating box ratio
    return box_ratio

def one_period_emv(dist_moved,box_ratio):
    one_period_emv=dist_moved/box_ratio    #function calculating one period emv from distance nmoved and box ratio
    return one_period_emv

for i in range(1,len(high)):
    distMoved=dist_moved(high[i],low[i],high[i-1],low[i-1])    #calculation of emvs and storing them in that list created
    boxRatio=box_ratio(high[i],low[i],volume[i])
    oneEmv=one_period_emv(distMoved,boxRatio)
    list_emvs.append(oneEmv)

onePeriod={'one_period':list_emvs} #made this into dict type and then to daataframe as using rolling function
oneperiod=pd.DataFrame(onePeriod)

emv_14=oneperiod.one_period.rolling(14).mean()
EMV=list(emv_14)  #first 13 will be NaN as after 14 day we will get first 14 period EMV

dataframe={'Close':close,'High':high,'Low':low,'One Period EMV':list_emvs,'14 period EMV':EMV}
data=pd.DataFrame(dataframe)
data

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low One Period EMV  14 period EMV
Date
2021-05-24  202.146667  204.826660  191.216660            NaN            NaN
2021-05-25  201.563339  204.663330  198.570007      26.072541            NaN
2021-05-26  206.376663  208.723328  200.500000      28.665535            NaN
2021-05-27  210.283340  210.376663  205.403336      20.609109            NaN
2021-05-28  208.406662  211.863327  207.460007      11.436893            NaN
...                ...         ...         ...            ...            ...
2023-05-16  166.520004  169.520004  164.350006      -1.157168       5.319231
2023-05-17  173.860001  174.500000  167.190002      22.779343       7.165245
2023-05-18  176.889999  177.059998  172.449997      16.458213       6.220706
2023-05-19  180.139999  181.949997  176.309998      18.140153       7.547048
2023-05-22  188.869995  189.320007  180.110001       38.96773       9.908500

[503 rows x 5 columns]